### ISSUE TITLE
Models.py

### ISSUE THREAD

**Issue by voffan** [voffan/abit-anketa#1]
В Person указать related name для родителей
Изменить type в attribute добавить к нему verbose_name
eduform преобразовать в CharField и добавить Choices
попробовать сделать syncdb

**Comment by st-pi** [comment]
60cc, npu MurpaLLuu BblBoguT OLLlu6ky :<
C:\Users\dno\Desktop\ucheba\git\abit-anketa>manage.py migrate
Operations to perform:
  Synchronize unmigrated apps: anketa
  Apply all migrations: sessions, contenttypes, auth, admin
Synchronizing apps without migrations:
  Creating tables...
  Installing custom SQL...
  Installing indexes...
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\apps\config.py", line 163, in get_m
odel
    return self.models[model_name.lower()]
KeyError: 'universal_directory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\serializers\python.py", line 1
56, in _get_model
    return apps.get_model(model_identifier)
  File "C:\Python34\lib\site-packages\django\apps\registry.py", line 202, in get
_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "C:\Python34\lib\site-packages\django\apps\config.py", line 166, in get_m
odel
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'anketa' doesn't have a 'universal_directory' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\serializers\json.py", line 75,
 in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "C:\Python34\lib\site-packages\django\core\serializers\python.py", line 9
3, in Deserializer
    Model = _get_model(d["model"])
  File "C:\Python34\lib\site-packages\django\core\serializers\python.py", line 1
58, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_ide
ntifier)
django.core.serializers.base.DeserializationError: Invalid model identifier: 'an
keta.universal_directory'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dno\Desktop\ucheba\git\abit-anketa\manage.py", line 10, in <mod
ule>
    execute_from_command_line(sys.argv)
  File "C:\Python34\lib\site-packages\django\core\management__init__.py", line
385, in execute_from_command_line
    utility.execute()
  File "C:\Python34\lib\site-packages\django\core\management__init__.py", line
377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python34\lib\site-packages\django\core\management\base.py", line 288,
 in run_from_argv
    self.execute(_args, *_options.**dict**)
  File "C:\Python34\lib\site-packages\django\core\management\base.py", line 338,
 in execute
    output = self.handle(_args, *_options)
  File "C:\Python34\lib\site-packages\django\core\management\commands\migrate.py
", line 128, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)

  File "C:\Python34\lib\site-packages\django\core\management\commands\migrate.py
", line 298, in sync_apps
    call_command('loaddata', 'initial_data', verbosity=self.verbosity, database=
connection.alias, skip_validation=True, app_label=app_label, hide_empty=True)
  File "C:\Python34\lib\site-packages\django\core\management__init__.py", line
115, in call_command
    return klass.execute(_args, *_defaults)
  File "C:\Python34\lib\site-packages\django\core\management\base.py", line 338,
 in execute
    output = self.handle(_args, *_options)
  File "C:\Python34\lib\site-packages\django\core\management\commands\loaddata.p
y", line 61, in handle
    self.loaddata(fixture_labels)
  File "C:\Python34\lib\site-packages\django\core\management\commands\loaddata.p
y", line 91, in loaddata
    self.load_label(fixture_label)
  File "C:\Python34\lib\site-packages\django\core\management\commands\loaddata.p
y", line 142, in load_label
    for obj in objects:
  File "C:\Python34\lib\site-packages\django\core\serializers\json.py", line 81,
 in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2]
)
  File "C:\Python34\lib\site-packages\django\utils\six.py", line 658, in reraise

```
raise value.with_traceback(tb)
```

  File "C:\Python34\lib\site-packages\django\core\serializers\json.py", line 75,
 in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "C:\Python34\lib\site-packages\django\core\serializers\python.py", line 9
3, in Deserializer
    Model = _get_model(d["model"])
  File "C:\Python34\lib\site-packages\django\core\serializers\python.py", line 1
58, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_ide
ntifier)
django.core.serializers.base.DeserializationError: Problem installing fixture 'C
:\Users\dno\Desktop\ucheba\git\abit-anketa\anketa\fixtures\initial_data.json': I
nvalid model identifier: 'anketa.universal_directory'
ЧтО с .JsOn ФаЙлОм ДеЛаТь???

**Comment by voffan** [comment]
Подумай над тем, а что происходит с абитуриентом, если его зачисляют? Надо одбавить состояние абитуриента.
